name: CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest
        container: ghcr.io/sitkoru/actions-container
        steps:
            -   uses: actions/checkout@v2
            -   uses: actions/setup-dotnet@v1
                with:
                    dotnet-version: '5.0.x'
            -   name: Download protoc and protoc-doc-gen
                working-directory: build
                run: |
                    ./build.sh
            -   name: Create package
                run: dotnet pack -c Release
