name: CI

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest
        container: ghcr.io/sitkoru/actions-container
        steps:
            -   uses: actions/checkout@v2.3.4
            -   uses: actions/setup-dotnet@v1
                with:
                    dotnet-version: '5.0.x'
            -   name: Download protoc and protoc-doc-gen
                working-directory: build
                run: |
                    chmod +x download.sh
                    ./download.sh
            -   name: Create package
                run: dotnet pack -c Release src/Sitko.Grpc.Tools.Doc
